name:  deploy vue to ecs
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      # 发布到远程
      - name: npm install
        run: |
          npm install
          npm run build
          pwd
      # Deploy
      - name: Deploy to Server  # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0  # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.ANOTHER_DEPLOY_KEY }}   # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc'   # rsync参数，排除.pyc文件
          SERVER_PORT: '22'  # SSH端口
          FOLDER: ./  # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.ANOTHER_USER_HOST }}  # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.SSH_USER_NAME }}  # 引用配置，服务器登录名
          SERVER_DESTINATION: /home/mysite/   # 部署到目标文件夹
      # Docker build
      - name: Docker  build  and  run  # 第三步，打包项目并构建镜像
        run: |
          cd /home/runner/work/github-action-study/github-action-study
          ls
          docker-compose up -d
        env:
          CI: true
